
image:
  repository: placeholder
  # defaults to appVersion
  tag: upstream
  pullPolicy: IfNotPresent

metallb:
  # configInline specifies MetalLB's configuration directly, in yaml
  # format. When configInline is used, Helm manages MetalLB's
  # configuration ConfigMap as part of the release, and
  # existingConfigMap is ignored.
  #
  # Refer to https://metallb.universe.tf/configuration/ for
  # available options.
  configInline: {}

  prometheus: {}