---
{{- include "common.deployment.common_config" . | nindent 0 }}
spec: {{ include "common.deployment.common_spec" . | nindent 2 }}
  template: {{ include "common.deployment.pod.metadata" . | nindent 4 }}
    spec:
      serviceAccountName: {{ include "common.names.serviceAccountName" . | quote }}
      containers:
        - name: {{ .Chart.Name }}
          {{- include "common.containers.imageConfig" .Values.image | nindent 10 }}
          args: [ "-conf", "/etc/coredns/Corefile" ]
        {{- if .Values.secure }}
          securityContext:
            runAsUser: 1000
        {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/coredns
          ports:
            - {containerPort: 53, protocol: UDP, name: dns-udp}
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8181
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "common.names.fullname" . }}
            items:
              - key: Corefile
                path: Corefile
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}

