apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.service.loadBalancer }}
    {{- if .Values.service.loadBalancer.address_pool }}
    metallb.universe.tf/address-pool: {{ .Values.service.loadBalancer.address_pool }}
    {{- end }}
    {{- end }}
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
spec:
  selector:
    {{- include "common.labels.selectorLabels" . | nindent 6 }}
  type: LoadBalancer
  {{- if .Values.service.loadBalancer }}
  {{- if .Values.service.loadBalancer.IP }}
  loadBalancerIP: {{ .Values.service.loadBalancer.IP }}
  {{- end }}
  {{- end }}
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: dns-udp
  {{- if not (empty .Values.service.externalTrafficPolicy)}}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- with .Values.service.externalIPs}}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
  {{- toYaml . | nindent 6 }}
  {{- end -}}